var map_def_data = [' AAAAAAAAAAAAAA      AAAAAAAA             AAAAAAAAA',
                    'AaaaaaaaaaaaaaA     AaaaaaaaA         AAAAaaaaa0aaA',
                    ' AAAAAAAAAAAAaA      AaAAAAAaA AAAAAAAAaaAaaAAAAAAA',
                    '           AaAAAAAAAAAaA  AaaAAaaaaaaaaAaAaaA ',
                    '       AAAAAaAaaaaaaaaaaA AaAaAAaAAAAAAAaAaaA ',
                    '      AaaaaaAaAAAAAAAAAA AaAAaAAaA   AaaAAAaA',
                    '      AaAAAAAaA          AAAAAaAAaA  AaAAaaaA',
                    '     AaaaaaaaA          AaaaaaaAAaA  AaaaAAA',
                    '      AAAAAAAA      AA  AaAAAAAAAaA   AAAA',
                    '                   AaA AaA     AaA ',
                    '                    AaAAaAA    AaA ',
                    '                    AaaaaaA   AaA ',
                    '                     AaAAAaAAAAaA ',
                    '                    AaA AaaaaAaA ',
                    '                    AaA AaAAaAaA ',
                    '                   AaA AaAAaAaA ',
                    '                    AA AaAAaAaA ',
                    '                      AaAaaAaA ',
                    '                      AaAAAAaA ',
                    '                     AaaaaaaA ',
                    '                      AAAAAAA '];

var map_def_entities = [new Text("Use A / D to move", 5, -3),
                        new Text("E / Z", 17, 1),
                        new Text("W / X", 28, -3),
                        new Text("W", 27, 9), new Text("E", 28, 9), new Text("D", 29, 10), new Text("X", 28, 11), new Text("Z", 27, 11), new Text("A", 27, 10),
                        ];
let map_def = new Map("#22FF88", map_def_data, [1, 1], map_def_entities, ["map_wd1"])

    var map_wd1_data = ['        AAAAAAAAA    ',
                        '       AaaaaaaaaA    ',
                        '       AaaaaaaaaaA   ',
                        '      AaaaaaaaaaaA   ',
                        '      AaaaaaaaaaaaA  ',
                        '     AaaaaaaaaaaaaA  ',
                        '     AaaaaaaaaaaaaaA ',
                        '     AaaaaaaaaaaaaA  ',
                        '      AaaaaaaaaaaaA  ',
                        '      AaaaaaaaaaaA   ',
                        '       AaaaaaaaaaA   ',
                        '       AaaaaaaaaA    ',
                        '        AaaaAAAAA    ',
                        '       AaaaA         ',
                        '        AaaA         ',
                        '       AaaA          ',
                        ' AAAAAAAaaAAAAAAAAAAA',
                        'AaaaaaaaaaaAAaaaaaaaA',
                        ' AAAAAAAAAAaAaAAAAAaaA',
                        '         AaAAaA   AaaA',
                        '          AaAaA   AaaaA',
                        '       AAAaAAaA  AaaaaA',
                        '       AaaaaaAaA AaaaaaA',
                        '       AAaaAAaA  AaaaaA',
                        '       AaaaaaAaA AaaaaaA',
                        '       AAaaAAaA  AaaaaA',
                        '       AaaaaaAaA AaaaaaA',
                        '       AAaaAAaA  AaaaaA',
                        '         AaaaaA   AaaaA',
                        '         AAAAA    AaaA',
                        '                   AaA',
                        '                   AA'];

    var map_wd1_entities = [new Text("Welcome", 2, 13), 
                            new Text("to the field!", 3, 14), 
                            new Text("There are trials", 4, 20)];
    let map_wd1 = new Map("#22FF88", map_wd1_data, [1, 17], map_wd1_entities, []);

